language: java

sudo: true

jdk:
  openjdk11

services:
  mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - mysql -uroot -proot


after_success:
  - bash <(curl -s https://codecov.io/bash)

env: CODECOV_TOKEN="7c0cfc3d-b778-4066-aede-01da1a63d827"
