language: java

sudo: false

jdk:
  openjdk11

services:
  - mysql

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - mysql -u root --password=root < travis.sql

env: CODECOV_TOKEN="7c0cfc3d-b778-4066-aede-01da1a63d827"
